#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
FAQ dos artigos, extraído dos HTMLs publicados (PR #8 e seguintes).

Motivo de existir: aquele FAQ foi escrito direto no HTML final, que é gerado
por _build.py a partir de _bodies. Sem este arquivo, o próximo build apagaria
o trabalho. Aqui o conteúdo vira fonte, e o build volta a ser reproduzível.
Editar o FAQ de um artigo: alterar aqui e rodar _build.py.
"""

FAQ = {
    "automacao-de-whatsapp-para-clinicas": [
        ("O que é automação de WhatsApp para clínicas?",
         "É o uso de um sistema que responde, organiza e acompanha as conversas do WhatsApp da clínica sem depender de alguém digitando tudo manualmente. Na prática, ela cuida das tarefas repetitivas, como responder o primeiro contato, confirmar consulta e lembrar o paciente, enquanto a equipe fica livre para o atendimento que exige gente de verdade."),
        ("Automatizar o WhatsApp da clínica pode gerar bloqueio?",
         "Pode, se for feito errado. Disparo em massa para quem não pediu contato, volume alto de mensagens em pouco tempo e número novo já saindo atirando são os principais gatilhos de bloqueio. O caminho seguro é responder quem procurou a clínica, respeitar ritmo humano de conversa e aquecer o número antes de escalar."),
        ("Qual a diferença entre automação e IA de atendimento?",
         "Automação segue uma regra fixa: se acontecer isso, envie aquilo. A IA interpreta o que o paciente escreveu e responde de forma diferente conforme o caso, tirando dúvida sobre procedimento, valor ou horário. As duas se complementam, e a maioria das clínicas usa automação para lembretes e IA para a conversa em si."),
        ("Preciso da API oficial do WhatsApp para automatizar?",
         "Não para começar. Dá para operar conectando o número da clínica ao sistema, que é o suficiente para a maior parte das clínicas. A API oficial faz sentido quando o volume cresce, quando se quer mais estabilidade e quando a clínica precisa de vários atendentes no mesmo número com segurança."),
        ("O que dá para automatizar sem o atendimento ficar robótico?",
         "Resposta imediata ao primeiro contato, confirmação de consulta, lembrete antes do horário, retomada de quem sumiu e pesquisa de satisfação. O que não se automatiza é negociação, contorno de objeção e acolhimento de paciente inseguro. A régua é simples: automatize o previsível, mantenha humano o que envolve decisão."),
    ],
    "captacao-pacientes-harmonizacao-facial": [
        ("Como captar pacientes para harmonização facial?",
         "Comunique critério, naturalidade do resultado e avaliação individual em vez de preço na chamada. Isso reduz o volume de curiosos e aumenta o número de interessados reais. Depois disso, o que decide é responder rápido, conduzir a conversa antes de informar valor e manter follow-up durante o tempo de decisão."),
        ("Por que os leads de estética somem depois de perguntar o preço?",
         "Porque valor sem contexto sempre parece caro. Quando a primeira resposta é só o preço, a pessoa não tem como comparar nada além de número. A sequência que converte acolhe, pergunta o que incomoda, trata o medo de resultado artificial, explica o processo e só então fala de investimento."),
        ("Quanto tempo leva a decisão de um procedimento estético?",
         "Costuma levar mais que outros atendimentos de saúde, porque é eletivo, tem ticket alto e envolve pesquisa e comparação. Semanas entre o primeiro contato e o fechamento é normal. Quem fica com o paciente é a clínica que continuou presente nesse período sem incomodar."),
        ("Posso publicar antes e depois de harmonização facial?",
         "Depende do conselho da sua categoria profissional e do formato. Em qualquer caso, imagem de paciente exige autorização específica e por escrito para aquela finalidade, informando onde e por quanto tempo será usada. Quando o visual não é viável, depoimento sobre a experiência e conteúdo sobre critério funcionam bem."),
        ("Qual indicador acompanhar na captação de estética?",
         "Tempo até a primeira resposta, quantos contatos viraram avaliação, quantas avaliações viraram procedimento, quantos leads seguem em follow-up ativo e o custo por paciente. Esse último importa muito mais que o custo por lead, porque campanha com lead barato e conversão ruim sai mais cara no fim."),
    ],
    "comissao-de-dentistas-como-calcular": [
        ("Como calcular a comissão de um dentista?",
         "Defina primeiro a base de cálculo, que importa mais que o percentual. Existem três modelos: sobre receita bruta, sobre receita líquida (descontando impostos, taxa de cartão e custos diretos) e sobre o lucro. A líquida costuma ser o melhor equilíbrio entre justiça e simplicidade para a maioria das clínicas."),
        ("Qual o percentual de comissão mais praticado?",
         "A faixa mais citada no mercado brasileiro fica entre 30% e 50%, variando conforme especialidade, senioridade, quem traz o paciente e quem banca o material. O percentual isolado não diz muito: 40% sobre o bruto e 40% sobre o líquido produzem resultados bem diferentes para a clínica."),
        ("A comissão deve ser paga no fechamento ou no recebimento?",
         "Pagar conforme o recebimento é mais sustentável, porque alinha a saída de caixa com a entrada e resolve sozinho a questão da inadimplência: se a parcela não foi paga, não há comissão sobre ela. Pagar no fechamento de tratamento longo obriga a clínica a desembolsar antes de receber."),
        ("O que fazer quando o paciente não paga?",
         "A regra precisa estar escrita antes de acontecer. As opções são devolver, descontar da próxima comissão ou a clínica absorver. Esse é o ponto que mais gera conflito e o que menos costuma aparecer em contrato. Pagar conforme o recebimento elimina a discussão."),
        ("Preciso de contrato com o dentista parceiro?",
         "Sim. A relação precisa estar formalizada com base de cálculo, percentual, prazo de pagamento e regra de inadimplência por escrito. Acordo verbal que funcionou por anos costuma virar litígio quando a parceria termina. Vale consultar um advogado especializado para o formato adequado ao seu caso."),
    ],
    "como-atrair-pacientes-clinica-odontologica": [
        ("Como atrair mais pacientes para uma clínica odontológica?",
         "Funciona em camadas: presença digital que gera confiança, conteúdo que educa e nutre, tráfego pago para acelerar a captação e um processo de atendimento que transforma o contato em consulta marcada. Clínica que só faz anúncio e não organiza o atendimento gasta mais e agenda menos."),
        ("Quanto tempo leva para o marketing odontológico dar resultado?",
         "Depende do canal. Tráfego pago traz contato nos primeiros dias, mas só vira paciente se alguém responder rápido. Conteúdo e presença digital levam meses para maturar, porém sustentam a captação sem depender de verba diária. O ideal é rodar os dois, com o pago financiando o curto prazo enquanto o orgânico se consolida."),
        ("Vale mais investir em tráfego pago ou em conteúdo?",
         "Tráfego pago é aluguel de atenção, para quando você quer agenda cheia agora. Conteúdo é patrimônio, gera contato mesmo quando você para de pagar. Clínica que só faz pago fica refém do orçamento, e clínica que só faz orgânico demora a crescer. A combinação é o que dá previsibilidade."),
        ("De que adianta atrair paciente se a agenda não enche?",
         "De nada, e esse é o erro mais caro. A maior parte da perda não está na captação, está no que acontece depois do contato: demora para responder, ausência de follow-up e nenhum registro de quem ficou pelo caminho. Antes de aumentar a verba, vale organizar o atendimento do que já chega."),
        ("Como transformar seguidor em paciente agendado?",
         "Dando um caminho claro para a conversa sair da rede social e ir para o WhatsApp, e ali respondendo rápido, qualificando o interesse e conduzindo até o agendamento. Seguidor que manda mensagem e recebe resposta horas depois normalmente já marcou em outro lugar."),
    ],
    "como-nao-perder-leads-no-whatsapp": [
        ("Por que clínicas perdem tantos leads no WhatsApp?",
         "Porque o WhatsApp comum não foi feito para gerenciar atendimento comercial. A conversa desce na lista, ninguém sabe quem já foi respondido, cada pessoa da equipe atende de um jeito e não existe registro de quem ficou sem retorno. O lead não é rejeitado, ele simplesmente some no meio das mensagens."),
        ("Qual o tempo ideal para responder um lead?",
         "O mais rápido possível, porque quem procura clínica raramente procura só a sua. A chance de conversão cai conforme os minutos passam, e o paciente costuma fechar com quem responde primeiro e tira a dúvida dele com clareza. Responder na hora vale mais do que responder perfeito depois."),
        ("Quantas vezes fazer follow-up antes de desistir de um lead?",
         "Mais do que a maioria das clínicas faz. Boa parte para no primeiro contato sem resposta, mas grande parte dos agendamentos aparece a partir da segunda ou terceira tentativa. O que muda o resultado é ter uma sequência definida, com espaçamento e mensagem pensada, em vez de insistir aleatoriamente."),
        ("WhatsApp comum serve para gerenciar os leads da clínica?",
         "Serve para conversar, não para gerenciar. Ele não mostra em que etapa cada paciente está, não avisa quem precisa de retorno hoje, não guarda histórico organizado e some junto com o celular de quem atendia. É por isso que clínicas em crescimento migram para um CRM com o WhatsApp integrado."),
        ("Como saber quantos leads a clínica está perdendo?",
         "Comparando quantos contatos chegaram com quantos viraram consulta marcada e comparecida, etapa por etapa. Sem esse registro, a perda fica invisível e a sensação de que está tudo certo se mantém. Quando o funil fica visível, normalmente aparece um gargalo específico, e não um problema geral."),
    ],
    "como-reduzir-faltas-no-show-consultas": [
        ("O que é no-show em uma clínica?",
         "É o paciente que marca a consulta e não aparece, sem avisar a tempo de encaixar outra pessoa. O custo não é só o horário vago: entra a estrutura parada, a equipe disponível e o paciente que poderia ter ocupado aquele espaço e ficou esperando vaga."),
        ("Por que os pacientes faltam à consulta?",
         "Esquecimento é a causa mais comum, mas não é a única. Também pesam o medo do procedimento, a insegurança com o valor, a marcação feita com muita antecedência e a falta de qualquer contato entre o agendamento e o dia. Cada motivo pede uma ação diferente, por isso lembrete sozinho não resolve tudo."),
        ("Como reduzir faltas em consultas na prática?",
         "Combinando confirmação ativa, lembrete no canal que o paciente realmente usa, contato mais próximo do horário, lista de espera para preencher a vaga que abriu e atenção especial a quem já faltou antes. O ganho vem do conjunto, não de uma medida isolada."),
        ("Lembrete por WhatsApp funciona para reduzir faltas?",
         "Funciona, e costuma ser o canal com melhor retorno, porque é onde o paciente já está e responde. O detalhe que faz diferença é permitir resposta: o lembrete que aceita um simples confirmar ou remarcar transforma uma falta silenciosa em um horário que a clínica consegue reaproveitar."),
        ("Dá para automatizar a confirmação de consulta?",
         "Sim, e é justamente onde a automação rende mais, porque é uma tarefa repetitiva, previsível e que ninguém gosta de fazer manualmente. O sistema dispara na hora certa, registra quem confirmou e destaca quem não respondeu, deixando para a equipe apenas os casos que exigem contato pessoal."),
    ],
    "crm-para-clinica-de-estetica": [
        ("O que é um CRM para clínica de estética?",
         "É o sistema que organiza toda a jornada do cliente, do primeiro contato à recompra, reunindo WhatsApp, histórico e etapas de negociação em um lugar só. Diferente de uma agenda, ele mostra em que ponto cada pessoa parou e o que precisa ser feito para avançar."),
        ("O que muda em um CRM de estética em relação a outras áreas da saúde?",
         "A estética vive de ticket alto, decisão mais demorada e, principalmente, de recompra. O cliente pesquisa, compara, adia e volta semanas depois. Por isso o acompanhamento de quem não fechou na hora e o retorno de quem já fez procedimento pesam muito mais no faturamento do que na maioria das outras áreas."),
        ("Como aumentar a recompra na clínica de estética?",
         "Sabendo quem fez o quê e quando, para retomar o contato no momento em que o procedimento pede manutenção ou o próximo passo faz sentido. Sem esse registro, a clínica só reencontra o cliente por acaso, normalmente quando ele já foi para a concorrente."),
        ("Vale a pena ter CRM em clínica de estética pequena?",
         "Vale quando o volume de contatos passa do que dá para lembrar de cabeça, o que acontece antes do que se imagina. O sinal clássico é perceber que existem pessoas interessadas que ninguém retomou. Os planos começam em R$ 297 por mês e há teste grátis de 7 dias, então dá para validar antes de decidir."),
        ("O que observar na hora de escolher um CRM para estética?",
         "Se o WhatsApp é integrado de verdade, se dá para ver o funil visualmente, se o follow-up é registrado e cobrado pelo sistema e se a equipe consegue usar sem treinamento longo. Ferramenta genérica de vendas costuma travar justamente na conversa e no acompanhamento, que é o coração da estética."),
    ],
    "crm-para-clinica-odontologica": [
        ("O que é um CRM para clínica odontológica?",
         "É o sistema que organiza os pacientes em potencial e o relacionamento com eles, do primeiro contato no WhatsApp até o tratamento fechado. Ele mostra em que etapa cada pessoa está, o que já foi conversado e quem precisa de retorno, coisa que agenda e prontuário não fazem."),
        ("Qual a diferença entre CRM e software de gestão odontológica?",
         "O software de gestão cuida de quem já é paciente: agenda, prontuário, faturamento. O CRM cuida de quem ainda não é: o contato que chegou pelo anúncio, pediu orçamento e está decidindo. São camadas diferentes e complementares, e a maioria das clínicas tem a segunda descoberta."),
        ("Quanto custa um CRM para clínica odontológica?",
         "No SaúdeCRM os planos vão de R$ 297 a R$ 687 por mês conforme o volume de leads e os recursos, com 7 dias grátis para testar. O cálculo que importa é comparar a mensalidade com o valor de um único tratamento recuperado, que na odontologia costuma pagar o sistema."),
        ("Vale a pena ter CRM em clínica odontológica pequena?",
         "Vale quando a clínica já investe em captação ou quando a recepção não dá conta de acompanhar todo mundo. Se os contatos ainda são poucos e todos recebem retorno no mesmo dia, dá para esperar. O problema aparece quando ninguém sabe dizer quantos orçamentos ficaram sem resposta."),
        ("Quanto tempo leva para implantar um CRM na clínica?",
         "A configuração inicial é rápida, questão de horas para começar a receber e organizar os contatos. O que leva algumas semanas é o hábito da equipe, registrar tudo no sistema e seguir a rotina de follow-up. Começar simples e ampliar depois funciona melhor do que tentar configurar tudo de uma vez."),
    ],
    "equipe-nao-consegue-acompanhar-leads": [
        ("Por que marketing e recepção vivem em conflito na clínica?",
         "Porque cada lado enxerga metade do processo. O marketing mostra o volume de contatos gerados, a recepção sente o volume de mensagens que não consegue responder, e nenhum dos dois tem um número comum para olhar. Sem registro compartilhado, a conversa vira opinião contra opinião."),
        ("Como saber se o problema é o lead ruim ou o atendimento?",
         "Medindo etapa por etapa. Se muitos contatos chegam e poucos são respondidos no mesmo dia, o gargalo é atendimento. Se todos são respondidos rápido e mesmo assim não avançam, o problema está na qualidade do contato ou na abordagem. Sem esse dado, a discussão não termina."),
        ("O que fazer quando a equipe não dá conta do volume de leads?",
         "Antes de contratar, vale organizar. Boa parte da sobrecarga vem de tarefa repetitiva, como responder a mesma dúvida, confirmar horário e lembrar paciente, que o sistema absorve. Depois disso é que fica claro se falta gente de verdade ou se faltava processo."),
        ("Como um CRM resolve esse conflito?",
         "Dando visibilidade a todo mundo sobre o mesmo funil: quantos entraram, quem respondeu, quem ficou parado e onde travou. A conversa deixa de ser sobre culpa e passa a ser sobre o ponto específico que precisa melhorar, com nome e etapa."),
        ("O que muda nos primeiros 30 dias com o processo organizado?",
         "Costuma aparecer primeiro o que estava invisível: contatos sem retorno, orçamentos parados e pessoas que ninguém retomou. Esse resgate inicial normalmente já traz agendamento, antes mesmo de qualquer aumento de investimento em captação."),
    ],
    "follow-up-de-pacientes": [
        ("O que é follow-up de pacientes?",
         "É o acompanhamento ativo de quem demonstrou interesse e não fechou. Envolve retomar o contato de forma planejada, lembrar o paciente do que ficou pendente e oferecer o próximo passo, em vez de esperar que ele volte sozinho, o que raramente acontece."),
        ("Por que os pacientes somem depois do orçamento?",
         "Quase nunca é falta de interesse. Normalmente o paciente adia a decisão, se assusta com o valor, precisa conversar com alguém antes ou simplesmente se distrai com a rotina. Sem alguém retomando, o assunto morre por inércia, não por recusa."),
        ("Quando e quantas vezes fazer follow-up?",
         "O primeiro retorno deve ser rápido, ainda com o assunto quente, e os seguintes espaçados ao longo dos dias e semanas seguintes. O erro mais comum é parar cedo demais: boa parte dos fechamentos acontece depois da primeira tentativa sem resposta."),
        ("O que escrever no follow-up para não parecer insistência?",
         "Mensagem curta, pessoal e com um motivo real para o contato, como tirar uma dúvida específica, informar uma condição ou oferecer um horário. O que soa chato é a cobrança repetida e igual. O que funciona é lembrar do contexto daquele paciente."),
        ("Vale a pena automatizar o follow-up?",
         "Vale para garantir que ele aconteça, que é onde a maioria falha. O sistema lembra a equipe de quem precisa de retorno hoje e dispara as etapas previsíveis, deixando o toque pessoal para os casos que exigem conversa. Follow-up que depende só de memória não sobrevive à rotina da clínica."),
    ],
    "funil-de-vendas-para-clinicas": [
        ("O que é funil de vendas em uma clínica?",
         "É o caminho que a pessoa percorre do primeiro contato até virar paciente em tratamento, dividido em etapas visíveis. Ele existe em toda clínica, mesmo nas que nunca desenharam: a diferença é que, sem mapear, ninguém sabe em qual etapa está perdendo gente."),
        ("Quais são as etapas do funil de uma clínica?",
         "Em geral: contato recebido, atendimento iniciado, avaliação ou consulta agendada, comparecimento, orçamento apresentado e tratamento fechado. Os nomes mudam conforme a especialidade, mas a lógica é a mesma, acompanhar a passagem de uma etapa para a outra."),
        ("Como saber onde está o gargalo do funil?",
         "Olhando a queda entre etapas, não o total. Se muita gente entra e pouca é atendida, o gargalo é resposta. Se todos são atendidos mas poucos agendam, é abordagem. Se agendam e não aparecem, é confirmação. Cada gargalo tem uma solução diferente."),
        ("Qual é uma boa taxa de conversão para clínica?",
         "Não existe número universal, porque varia muito por especialidade, ticket e origem do contato. O parâmetro mais útil é o seu próprio histórico: medir hoje, agir em um gargalo específico e comparar depois. Melhorar a própria taxa vale mais que perseguir uma média de mercado."),
        ("Como usar Kanban para gerenciar o funil da clínica?",
         "Cada paciente vira um cartão que caminha pelas colunas conforme avança. A vantagem é enxergar de imediato onde há acúmulo e quem está parado há tempo demais. É o formato mais simples para uma equipe adotar sem treinamento longo."),
    ],
    "indicadores-clinica-odontologica": [
        ("Quais indicadores uma clínica odontológica deve acompanhar?",
         "Os essenciais se dividem em captação, conversão, atendimento, operação, financeiro e retenção. Na prática, começa por quantos contatos chegam, quantos viram consulta, quantos comparecem, quantos fecham tratamento e quantos voltam. Esse encadeamento já mostra a saúde do negócio."),
        ("Por onde começar a medir se a clínica não mede nada hoje?",
         "Pelo caminho do paciente: contatos recebidos, consultas agendadas, comparecimento e tratamentos fechados. Esses quatro números revelam o principal gargalo e podem ser levantados sem sistema nenhum no começo. Complexidade demais logo de cara costuma fazer a medição ser abandonada."),
        ("O que é taxa de conversão em uma clínica odontológica?",
         "É a proporção de pessoas que avançam de uma etapa para a seguinte, por exemplo de contato para consulta agendada, ou de orçamento apresentado para tratamento fechado. Medir por etapa é mais útil que medir só o resultado final, porque mostra exatamente onde intervir."),
        ("Com que frequência acompanhar os indicadores?",
         "Os operacionais, como contatos sem resposta e confirmações pendentes, no dia a dia. Os de conversão e financeiro, mensalmente, para enxergar tendência sem reagir a oscilação de uma semana. O erro comum é olhar tudo todo dia e tomar decisão em cima de ruído."),
        ("Dá para acompanhar indicadores sem planilha manual?",
         "Sim, quando o registro acontece na própria operação. Se cada contato e cada etapa ficam no sistema durante o atendimento, os números saem sozinhos. A planilha manual costuma ser abandonada justamente porque exige um trabalho extra que ninguém sustenta."),
    ],
    "lgpd-para-clinicas": [
        ("A LGPD se aplica a consultório pequeno?",
         "Sim. Não existe isenção por porte. Clínica trata dado de saúde, que a lei classifica como dado pessoal sensível, a categoria de maior proteção. Isso vale igualmente para a rede com várias unidades e para o consultório de um único profissional."),
        ("O paciente pode exigir que eu apague o prontuário dele?",
         "Não integralmente. O Conselho Federal de Odontologia estabelece guarda mínima de dez anos, e essa obrigação legal convive com a LGPD. O paciente tem direito de acessar o próprio prontuário, pedir correção de informação incorreta e ser informado sobre o tratamento dos dados. O que pode ser excluído são dados usados para outras finalidades, como marketing."),
        ("Posso publicar foto de antes e depois do paciente?",
         "Só com autorização específica para essa finalidade, separada do termo de atendimento, informando onde e por quanto tempo a imagem será usada. Além da LGPD, há regras éticas próprias da profissão sobre esse tipo de publicação, que valem a consulta ao conselho da sua categoria."),
        ("Mandar prontuário por WhatsApp é problema?",
         "É um dos pontos mais frágeis da operação de clínica. Dado clínico trafegando por aplicativo pessoal, sem controle de acesso e armazenado no celular de cada pessoa, é exposição desnecessária. O caminho é centralizar a informação em um sistema com acesso por perfil."),
        ("O que perguntar ao fornecedor do meu sistema sobre LGPD?",
         "Onde ficam servidores e backups, se existe controle de acesso por perfil, se há registro de quem acessou o quê, se os dados de cada clínica ficam isolados, como você é avisado em caso de incidente e como funciona a exportação e a eliminação ao encerrar o contrato."),
    ],
    "melhores-sistemas-para-clinicas": [
        ("Qual o melhor sistema para clínica em 2026?",
         "Não existe um melhor absoluto, existe o certo para o problema que está custando mais caro agora. Se o vazamento é contato que chega e some, você precisa de um CRM. Se é prontuário em papel, de um sistema de gestão clínica. Se é lucro desconhecido, de um financeiro. Comparar categorias diferentes pelo preço é o erro mais comum."),
        ("Qual a diferença entre software de gestão e CRM para clínicas?",
         "O software de gestão cuida de quem já é paciente: prontuário, agenda, faturamento. O CRM cuida de quem ainda não é: o contato que chegou pelo anúncio, pediu orçamento e está decidindo. São camadas complementares, e clínicas que investem em captação normalmente precisam das duas."),
        ("Quanto custa um sistema para clínica?",
         "Varia conforme a categoria e o porte. No caso do SaúdeCRM, os planos vão de R$ 297 a R$ 687 por mês conforme o volume de leads, com 7 dias grátis. Ao comparar preços, verifique se a cobrança é por usuário, se há taxa de implantação e o que é vendido como pacote adicional."),
        ("Como testar um sistema antes de contratar?",
         "Use dado real e a equipe real durante o período de avaliação, não um cenário fictício. Conecte o WhatsApp, atende um turno inteiro, peça para a pessoa menos técnica executar uma tarefa sozinha, abra um chamado no suporte e tente exportar seus dados. Uma semana com esse roteiro revela mais que qualquer demonstração."),
        ("Posso usar CRM junto com o sistema de gestão que já tenho?",
         "Sim, e é o cenário mais comum em clínicas que já têm prontuário implantado. Cada sistema cuida de uma camada, e a integração entre eles evita retrabalho de cadastro. O SaúdeCRM integra com o Clinicorp justamente para esse tipo de convivência."),
    ],
    "precificacao-odontologica-hora-clinica": [
        ("Como calcular a hora clínica de uma clínica odontológica?",
         "Some todos os custos fixos e as despesas de estrutura do mês, calcule quantas horas de cadeira estão realmente disponíveis (cadeiras vezes horas por dia vezes dias úteis) e aplique a taxa de ocupação real da agenda. Divida o custo total pelas horas efetivamente ocupadas. O resultado é o piso: abaixo dele, cada hora atendida dá prejuízo."),
        ("O que entra no preço de um procedimento odontológico?",
         "Tempo de cadeira (hora clínica vezes a duração real, incluindo preparo e limpeza), material específico, laboratório quando houver, comissão do profissional, impostos, taxa de cartão conforme o parcelamento usado e, por último, a margem pretendida. A margem é o último item da conta, não o primeiro."),
        ("Posso usar o preço do concorrente como referência?",
         "Não como base de cálculo. A estrutura de custo dele é diferente da sua: ponto, aluguel, número de cadeiras, equipe e ociosidade mudam tudo. Além disso, é provável que ele também não tenha calculado. Preço de mercado serve para saber onde você está posicionado, não para definir o seu piso."),
        ("Por que o procedimento mais caro nem sempre é o mais lucrativo?",
         "Porque o que importa é quanto ele deixa por hora de cadeira ocupada, não o valor da tabela. Um tratamento de valor alto que ocupa muitas horas e consome material caro pode ter margem por hora menor que um procedimento simples e rápido. Ranquear por margem por hora costuma revelar que a clínica priorizava a agenda errada."),
        ("Com que frequência devo revisar os preços?",
         "No mínimo uma vez por ano, e sempre que houver reajuste de aluguel, aumento de folha, mudança de regime tributário, alteração no custo de material ou laboratório, ou mudança relevante na ocupação. Clínica que não revisa perde margem em silêncio, porque os custos sobem e o preço fica parado."),
    ],
    "publicidade-odontologica-o-que-pode": [
        ("Dentista pode publicar foto de antes e depois?",
         "A Resolução CFO-196/2019 passou a permitir a divulgação de imagens de diagnóstico e do resultado do tratamento pelo cirurgião-dentista, o que antes era vedado. O entendimento é que a permissão se refere ao profissional pessoa física; para a clínica pessoa jurídica isso é caracterizado como publicidade comercial e permanece restrito. Confirme com o CRO do seu estado."),
        ("O que é proibido na publicidade odontológica?",
         "Imagem do momento durante o procedimento, promessa ou garantia de resultado, sensacionalismo e alegações de ser o melhor ou único, desmerecer colegas, e mercantilização com urgência artificial, sorteio de procedimento ou promoção agressiva."),
        ("O que precisa constar no material de divulgação?",
         "Nome e número de inscrição no CRO, identificação do responsável técnico quando a divulgação for da clínica como pessoa jurídica, e a especificação da profissão de cirurgião-dentista. Muitas autuações nascem da ausência desses dados, não do conteúdo em si."),
        ("Preciso de autorização do paciente para usar a imagem dele?",
         "Sim, e específica para essa finalidade. O termo de atendimento não cobre uso em marketing. A autorização deve ser por escrito, informando onde a imagem será publicada e por quanto tempo, e o paciente pode revogá-la depois, o que obriga a retirada do conteúdo."),
        ("As regras valem também para anúncio pago?",
         "Valem integralmente, com um agravante: o anúncio tem alcance maior e é mais visível. Além disso, as plataformas de mídia têm políticas próprias para saúde e podem reprovar criativos com imagem de procedimento mesmo em casos que o conselho permitiria."),
    ],
    "quanto-custa-crm-para-clinica": [
        ("Quanto custa um CRM para clínica?",
         "No SaúdeCRM os planos vão de R$ 297 a R$ 687 por mês conforme o volume de leads ativos, com 7 dias grátis para testar. No mercado, o valor varia bastante conforme o modelo de cobrança: por volume, por usuário, por unidade ou com módulos vendidos à parte. Comparar apenas a mensalidade costuma esconder o custo real."),
        ("Como saber se o investimento em CRM se paga?",
         "Divida a mensalidade pelo seu ticket médio. O resultado mostra quantos tratamentos a mais por mês pagam a ferramenta. Na maioria das clínicas, um único tratamento recuperado já cobre o valor com folga, principalmente em odontologia e estética, onde o ticket é mais alto."),
        ("Existe CRM gratuito para clínicas?",
         "Existem ferramentas gratuitas genéricas, mas elas costumam não ter WhatsApp integrado de verdade nem se adaptar ao fluxo de uma recepção. O custo aparece de outra forma: tempo da equipe, informação espalhada e limite que trava justamente quando a clínica cresce. Vale testar versões de avaliação de ferramentas específicas para saúde antes."),
        ("O que costuma estar escondido além da mensalidade?",
         "Taxa de implantação, migração da base atual, treinamento da equipe, cobrança por excedente, multa de fidelidade e regra de reajuste. Some também o custo invisível de adoção: sistema difícil consome horas de recepção que valem mais que a própria mensalidade."),
        ("Quando ainda não vale a pena contratar um CRM?",
         "Quando o volume de contatos é baixo o suficiente para uma pessoa acompanhar de cabeça e todo mundo recebe retorno no mesmo dia. Nesse cenário o ganho não compensa o esforço de implantação. Também não vale se a expectativa for que o sistema crie sozinho um hábito de follow-up que ninguém vai executar."),
    ],
    "recorrencia-em-clinica-de-estetica": [
        ("Por que o paciente de estética não volta depois da primeira sessão?",
         "Raramente é insatisfação. As causas mais comuns são não ter entendido que existe um próximo passo, sair sem retorno agendado, não receber nenhum acompanhamento após o procedimento e a clínica simplesmente não lembrar dele depois. Todas evitáveis com processo."),
        ("Como aumentar a recorrência em clínica de estética?",
         "Explique o protocolo completo já na avaliação, faça o paciente sair com o próximo passo agendado, entre em contato depois do procedimento para acompanhar o resultado, registre o que foi feito e quando, e crie uma régua de retorno por tipo de procedimento em vez de depender da memória da equipe."),
        ("Vale a pena mandar promoção para a base de pacientes?",
         "Disparo em massa com desconto costuma desvalorizar o serviço, atrair quem só busca preço e ainda arriscar o número da clínica. Funciona melhor o contato pertinente: falar com quem fez determinado procedimento, no período em que a manutenção faz sentido, citando o contexto daquela pessoa."),
        ("O que fideliza um paciente de estética?",
         "Menos programa de pontos e mais relacionamento: lembrar do contexto da pessoa, acompanhar o resultado, explicar com calma em vez de empurrar pacote e transmitir a sensação de acompanhamento contínuo. Desconto atrai de volta quem já viria; relacionamento traz quem tinha esquecido e ainda gera indicação."),
        ("Quais indicadores de recorrência acompanhar?",
         "Taxa de retorno após a primeira sessão, intervalo médio entre visitas, protocolos concluídos versus abandonados, tamanho da base inativa há mais de um ano e receita por paciente ao longo do relacionamento. Esse último muda a forma de decidir quanto investir em captação."),
    ],
    "secretaria-ou-crm-atendimento-clinica": [
        ("Devo contratar mais uma secretária ou investir em um CRM?",
         "Depende de onde está a sobrecarga. Se a equipe gasta o dia em tarefa repetitiva, como responder a mesma dúvida, confirmar consulta e lembrar paciente, o sistema resolve mais barato. Se falta gente para acolher e negociar presencialmente, aí a contratação faz sentido. Muitas clínicas descobrem que precisavam de processo, não de mais uma pessoa."),
        ("O CRM substitui a secretária da clínica?",
         "Não. Ele assume o que é repetitivo e previsível, e devolve tempo para o que exige gente: acolher o paciente inseguro, contornar objeção, conduzir a negociação e cuidar de quem está na recepção. A função não some, ela deixa de ser sufocada por tarefa mecânica."),
        ("Quanto custa um CRM comparado a uma contratação?",
         "A mensalidade de um CRM fica em uma fração do custo total de um funcionário, que inclui salário, encargos, treinamento e férias. No SaúdeCRM os planos vão de R$ 297 a R$ 687 por mês. A comparação honesta considera também o que cada opção resolve, porque são coisas diferentes."),
        ("Quais são os sinais de que a recepção precisa de um CRM?",
         "Mensagem que fica sem resposta, ninguém sabe dizer quantos orçamentos estão parados, o atendimento muda conforme quem está na recepção e o histórico do paciente vive no celular de uma pessoa só. Quando isso aparece, o problema já não é esforço, é falta de sistema."),
        ("Como implantar sem a equipe se sentir ameaçada?",
         "Deixando claro que o sistema tira o trabalho chato, não o emprego, e envolvendo a recepção na configuração desde o começo. Começar por uma dor concreta que elas próprias reclamam, como esquecer de retornar paciente, costuma transformar resistência em adesão."),
    ],
    "secretaria-virtual-com-ia-para-clinicas": [
        ("O que é uma secretária virtual com IA para clínicas?",
         "É um atendente automático que conversa em linguagem natural pelo WhatsApp. Diferente do chatbot de menu numerado, ele interpreta texto livre e áudio, responde dúvidas sobre a clínica, qualifica o interesse e encaminha para agendamento ou para a equipe quando o caso exige uma pessoa."),
        ("A IA substitui a recepcionista da clínica?",
         "Não. Ela absorve o volume repetitivo e o plantão fora do horário, como dúvidas frequentes, confirmação e primeira resposta. O que exige julgamento, acolhimento e negociação continua sendo humano. Clínica que contrata esperando demitir costuma se frustrar, porque perde justamente quem sustentava o relacionamento."),
        ("A IA pode responder dúvidas clínicas do paciente?",
         "Não deve. IA não avalia caso, não diagnostica e não deve opinar sobre tratamento, tanto por risco assistencial quanto por questão ética e legal. A configuração correta encaminha esse tipo de pergunta para o profissional responsável."),
        ("Quais os riscos de uma IA mal configurada?",
         "Responder informação desatualizada com tom seguro, prometer horário ou condição que a clínica não cumpre, insistir depois do paciente pedir para parar e não ter saída rápida para um humano. Some a isso o cuidado com dado sensível, que é exigência da LGPD em informação de saúde."),
        ("Como testar uma IA de atendimento antes de contratar?",
         "Converse com ela como paciente: mande mensagem fora do roteiro, com erro de digitação e em áudio. Depois escreva que quer falar com uma pessoa e veja quanto tempo leva. Pergunte também de onde vem a informação que ela usa e quem ajuda a construir esse roteiro."),
    ],
    "software-de-gestao-ou-crm-para-clinica": [
        ("Qual a diferença entre software de gestão e CRM para clínica?",
         "O software de gestão cuida de quem já é paciente: prontuário, agenda, procedimentos e faturamento. O CRM cuida de quem ainda não é: o contato que chegou, pediu orçamento e está decidindo. Um responde o que foi feito no paciente, o outro responde quem está prestes a fechar e quem esfriou."),
        ("Minha clínica precisa dos dois sistemas?",
         "Depende do momento. Consultório pequeno que vive de indicação normalmente resolve com o sistema de gestão. Clínica que investe em anúncio e recebe contato todo dia precisa dos dois, e costuma ser a falta do CRM que está custando mais caro nesse cenário."),
        ("Por onde começar se eu precisar dos dois?",
         "Resolva primeiro o que gera risco, depois o que gera receita. Se o prontuário ainda é papel, comece pelo sistema de gestão, porque isso é conformidade e qualidade de registro. Se o prontuário já está digital e a dor é comercial, comece pelo CRM, onde o retorno costuma aparecer nas primeiras semanas."),
        ("O CRM substitui o sistema de gestão da clínica?",
         "Não. O CRM não guarda evolução clínica, imagens nem cumpre a função de prontuário. Ele cuida da etapa anterior, quando a pessoa ainda é um contato interessado. São camadas diferentes e na maioria das clínicas elas convivem."),
        ("Os dois sistemas conseguem se integrar?",
         "Sim, e a integração evita cadastrar a mesma pessoa duas vezes. O SaúdeCRM integra com o Clinicorp por esse motivo. Ao avaliar qualquer combinação, pergunte o que exatamente sincroniza, com que frequência e o que continua manual, porque integração no material de vendas nem sempre é integração no dia a dia."),
    ],
    "trafego-pago-para-dentistas": [
        ("Vale a pena investir em tráfego pago para dentistas?",
         "Vale quando existe estrutura para atender o que o anúncio gera. Anúncio traz contato rápido, mas contato que não é respondido vira dinheiro perdido. Antes de aumentar a verba, é mais rentável garantir que todo contato recebe resposta e acompanhamento."),
        ("Meta Ads ou Google Ads para clínica odontológica?",
         "São momentos diferentes. O Google captura quem já está procurando tratamento agora, com intenção mais avançada. O Meta apresenta a clínica para quem ainda não estava buscando, gerando volume maior a custo menor por contato. Muitas clínicas usam os dois com objetivos distintos."),
        ("Por que meus anúncios geram leads mas não geram pacientes?",
         "Porque o resultado não termina no clique. A perda costuma estar no intervalo entre o contato chegar e alguém responder, e na ausência de follow-up de quem não fechou na hora. O anúncio entrega o contato, o processo é que entrega o paciente."),
        ("Qual a diferença entre custo por lead e custo por paciente?",
         "Custo por lead é quanto se paga por um contato. Custo por paciente é quanto se paga por alguém que efetivamente sentou na cadeira. É o segundo que importa, porque campanha com lead barato e conversão ruim sai mais cara no fim do que a de lead caro e bem trabalhado."),
        ("O que o dentista pode e não pode anunciar?",
         "A publicidade odontológica tem regras específicas do conselho da categoria, com restrições sobre promessa de resultado, uso de imagem de antes e depois e apelo comercial. Vale conferir as normas vigentes antes de subir campanha, porque o custo de um anúncio irregular vai além da mídia."),
    ],
}
